version: '3.8'
services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-qweasdzxc1}
    restart: always
    healthcheck:
       test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}
  backend:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    restart: always